default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  username: root
  password: root123

development:
  <<: *default
  database: twitter_mysql


# test:
#   <<: *default
#   database: twitter_test


# production:
#   <<: *default
#   database: twitter_mysql
#   username: twitter
#   password: <%= ENV['TWITTER_DATABASE_PASSWORD'] %>
