default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
   <<: *default
   database: twitter_pg
   username: postgres
   password: root123

# test:
#   <<: *default
#   database: twitter_test

# production:
#   <<: *default
#   database: twitter_pg